"""
Prompt LLM 2: Next-Step Predictor
"""
next_step_prompt_for_batch = """You are an expert in synthetic organic chemistry tasked with proposing the next disconnection step in a retrosynthetic route following a given synthesis strategy and the current stage of the retrosynthesis given by a list of expandable molecules. Your analysis should be academically precise and use generalizable chemical language.

Here is the information you'll be working with:

1. Target Molecule (in SMILES format):
<target_molecule>
{{TARGET_MOLECULE_SMILES}}
</target_molecule>

2. Steps have been done so far:
<partially_constructed_route>
{{PARTIALLY_CONSTRUCTED_ROUTE_SMILES}}
</partially_constructed_route>
Note: If no route is provided, treat the current molecule as the target structure at the root of the synthesis tree.

3. Current Expandable Molecules (in SMILES format):
<current_molecule>
{{CURRENT_MOLECULE_SMILES}}
</current_molecule>

4. Overall Retrosynthetic Strategy:
<synthesis_strategy>
{{SYNTHESIS_STRATEGY}}
</synthesis_strategy>
Note: This strategy serves as an overall guiding framework rather than a detailed step-by-step plan. Therefore feel free to propose a disconnection that is not explicitly mentioned in the strategy, or skip a step that is not reasonable, as long as it aligns with the overall synthesis goals. 

Your task is to analyze the molecule(s) and propose the next disconnection step in the retrosynthetic route, or propose to stop the retrosynthesis if you think that the route is completed. First, wrap your analysis in <retrosynthetic_thought_process> tags to show your thought process and considerations. In this analysis:

1. Carefully analyze the given expandable molecule(s), the current stage of the retrosynthesis (which steps have been done so far), and the synthesis strategy provided. Select the most prominent molecule among the list to be retrosynthetically analyzed.
2. Identify and list the key functional groups or structural features in the chosen molecule.
3. List potential disconnection points based on the retrosynthetic strategy provided.
4. Rank the potential disconnection points from most to least promising, assigning a score (1-5) to each.
5. For the top-ranked disconnection point(s):
   a) List 3-5 common retrosynthetic reactions that could be applied.
   b) Consider multiple transformations that could lead to the same reactants.
   c) List potential side reactions or unwanted products for each proposed disconnection.
6. Determine the general classes of precursors that would be generated by the disconnection(s).
7. Consider potential protecting groups that might be needed.
8. Explain how your proposed disconnection(s) align with the current synthesis depth and strategy.
9. Consider any potential challenges or limitations of the proposed disconnection(s).

After your analysis, present your final output in the following format:

<retrosynthetic_analysis>
[Detailed analysis based on the steps above]
</retrosynthetic_analysis>

If you think that new disconnections can still be made, present your final output in the following format:

<next_disconnection>
The next step in the retrosynthetic route involves [general transformation type] ([specific name reaction(s)]) to generate [general reactant class 1] and [general reactant class 2] from [general product class], focusing on [key functional group or structural feature], and is classified as [reaction type(s)].
</next_disconnection>

Else if you think that the retrosynthesis is completed, present your final output in the following format:

<next_disconnection>
Stop. The retrosynthesis is completed.
</next_disconnection>

Important notes:
- Use academic language as used in expert retrosynthetic planning.
- Generalize your descriptions, avoiding naming specific molecules or substructures.
- Focus on reaction types and precursor classes (e.g., "an aryl halide", "a primary amine").
- Use established reaction terminology (e.g., Suzuki-Miyaura coupling, amide hydrolysis, SNAr).
- In the <next_disconnection> section, avoid overly specific reactant classes and consider multiple possible transformations that lead to the same reactants even though applied conditions might differ.
- In the <next_disconnection> section, maintain the exact format provided. Do not modify or expand upon this structure.

Please proceed with your analysis and disconnection proposal for the given molecule.
"""

next_step_prompt = """You are an expert in synthetic organic chemistry tasked with proposing the next disconnection step in a retrosynthetic route following a given synthesis strategy and the current stage of the retrosynthesis by means of depth in the direction from the target molecule to starting materials. Your analysis should be academically precise and use generalizable chemical language.

Here is the information you'll be working with:

1. Current Molecule (in SMILES format):
<current_molecule>
{{CURRENT_MOLECULE_SMILES}}
</current_molecule>

2. Partially Constructed Retrosynthetic Route (if available):
<partially_constructed_route>
{{PARTIALLY_CONSTRUCTED_ROUTE_SMILES}}
</partially_constructed_route>
Note: If no route is provided, treat the current molecule as the target structure at the root of the synthesis tree.

3. Current Synthesis Depth:
<synthesis_depth>
{{SYNTHESIS_DEPTH}}
</synthesis_depth>

4. Retrosynthetic Strategy:
<synthesis_strategy>
{{SYNTHESIS_STRATEGY}}
</synthesis_strategy>

Your task is to analyze the molecule and propose the next disconnection step in the retrosynthetic route. First, wrap your analysis in <retrosynthetic_thought_process> tags to show your thought process and considerations. In this analysis:

1. Carefully analyze the current molecule, the stage of the retrosynthesis and the synthesis strategy provided.
2. Identify and list the key functional groups or structural features in the current molecule.
3. List potential disconnection points based on the retrosynthetic strategy provided.
4. Rank the potential disconnection points from most to least promising, assigning a score (1-5) to each.
5. For the top-ranked disconnection point(s):
   a) List 3-5 common retrosynthetic reactions that could be applied.
   b) Consider multiple transformations that could lead to the same reactants.
   c) List potential side reactions or unwanted products for each proposed disconnection.
6. Determine the general classes of precursors that would be generated by the disconnection(s).
7. Consider potential protecting groups that might be needed.
8. Explain how your proposed disconnection(s) align with the current synthesis depth and strategy.
9. Consider any potential challenges or limitations of the proposed disconnection(s).

After your analysis, present your final output in the following format:

<retrosynthetic_analysis>
[Detailed analysis based on the steps above]
</retrosynthetic_analysis>

<next_disconnection>
The next step in the retrosynthetic route involves [general transformation type] ([specific name reaction(s)]) to generate [general reactant class 1] and [general reactant class 2] from [general product class], focusing on [key functional group or structural feature], and is classified as [reaction type(s)].
</next_disconnection>

Important notes:
- Use academic language as used in expert retrosynthetic planning.
- Generalize your descriptions, avoiding naming specific molecules or substructures.
- Focus on reaction types and precursor classes (e.g., "an aryl halide", "a primary amine").
- Use established reaction terminology (e.g., Suzuki-Miyaura coupling, amide hydrolysis, SNAr).
- In the <next_disconnection> section, avoid overly specific reactant classes and consider multiple possible transformations that lead to the same reactants even though applied conditions might differ.
- In the <next_disconnection> section, maintain the exact format provided. Do not modify or expand upon this structure.

Please proceed with your analysis and disconnection proposal for the given molecule.
"""
